# General
mixed-port: 7890
redir-port: 7892
external-ui: ./
log-level: info
allow-lan: true
bind-address: "*"
external-controller: 127.0.0.1:9090
secret: ""
#---------------------------------------#
# Profiles
mode: rule
ipv6: false
authentication:
hosts:

dns:
  enable: true
  ipv6: false
  listen: 127.0.0.1:53
  enhanced-mode: redir-host
  nameserver:
    - 223.6.6.6
    - 223.5.5.5
  fallback: 
    - 208.67.222.222
    - 208.67.220.220
